statisticsnorway/ssb-project-cli

- src/ssb_project_cli/ssb_project/app.py
- tests/test_app.py
Enforces team name convention (only contain alphanumeric characters and/or underscores).
Added support for fetching GitHub PAT from .git-credentials.
If the user does not supply GitHub credentials but wants to create a repo, the cli will check for them in .git-credentials. The user can then choose between the GitHub users available.
> Get GitHub token form env

- .flake8
- .vscode/settings.json
- src/ssb_project_cli/ssb_project/app.py
- tests/test_app.py
Limit to ASCII characters, numbers, underscores, hyphens
> STAT-135: Improve validity checking of repo names

- src/ssb_project_cli/ssb_project/build/build.py
Should now print the correct icon instead of :twisted_rightwards_arrows when onprem environment is detected.
> Use rich print

- poetry.lock
- src/ssb_project_cli/__main__.py
- src/ssb_project_cli/ssb_project/app.py
- src/ssb_project_cli/ssb_project/create/create.py
- tests/test_help.py
- Poetry update
- Remove colour from usage text
- Correct URLs, tidy printing
- ~Add --version flag~ (reverted)
We could not remove the cyan colour from the commands, since this is [defined internally in a Typer function](https://github.com/tiangolo/typer/blob/e3f746793f443ea16ce9f0ef182e62ef698a0bba/typer/rich_utils.py#L493) and not exposed in any way for modification.
> STAT-169: Remove colours from help text

- src/ssb_project_cli/ssb_project/clean/clean.py
- tests/clean_test/test_clean.py
Cause of bug: 
-execute_command method supports commands in string and list formats. 
- bug caused by passing in command in list format
> Pass in argument as string

- src/ssb_project_cli/ssb_project/clean/clean.py
Seems like kernelspec was adding some new "%s" signs... (may be a temporary bug?)
Removing %s-s from kernelspec list, and stripping before making dictionary fixes the issue.
Reported by @aosthus
> Clean was not cleaning kernels

- poetry.lock
- pyproject.toml
- src/ssb_project_cli/ssb_project/__init__.py
- src/ssb_project_cli/ssb_project/app.py
- src/ssb_project_cli/ssb_project/clean/clean.py
- src/ssb_project_cli/ssb_project/create/create.py
- src/ssb_project_cli/ssb_project/create/github.py
- src/ssb_project_cli/ssb_project/create/local_repo.py
- src/ssb_project_cli/ssb_project/util.py
- tests/unit/create_test/test_github.py
- tests/unit/create_test/test_local_repo.py
This pr fixes the create --github bug, that occurred after access to api.github was changed onprem. 
Changes:
- Set the CA bundle to use when creating github and requests onprem.
- As the [user endpoint](https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28) is no longer available onprem, we prompt the user to provide their username if they are on-premises.
- Created a custom black/white style for autocomplete prompts to ensure readability.
NOTE: Org member list is retived by direct api calls to https://api.github.com/orgs/{GITHUB_ORG_NAME}/members. This could be solved cleaner with pygithub, but it uses the `/organizations/5849578/members` endpoint and this is also blocked onprem. Since it does not have the org name as part of the url we would have to do a security assessment …
> Fix create --github bug onprem

- src/ssb_project_cli/ssb_project/util.py
- tests/unit/utils_test.py
If the user has not encountered an error with ssb-project before or had deleted the ssb-project folder logging would raise an error when setting the output log-file.
- Added check for if the folder exists, if not then ssb-project will create it.
- Added a test case for the issue.
> Create log subfolders

- pyproject.toml
- src/ssb_project_cli/ssb_project/build/poetry.py
Updated the 'poetry source add' command to use the '--priority=primary' option instead of the deprecated '--default' option. This change resolves the build issue related to the deprecated key in the pyproject.toml configuration file for the 'nexus' source onprem.
When testing the changes oprem, the uhv-oljegass project builds successfully:
> Fix deprecated 'default' option in poetry source command

- .github/workflows/constraints.txt
- pyproject.toml
- src/ssb_project_cli/ssb_project/build/build.py
- src/ssb_project_cli/ssb_project/build/poetry.py
- tests/unit/build_test/test_build.py
- tests/unit/build_test/test_files/test_nexus_source_add_pyproject.toml
- tests/unit/build_test/test_files/test_nexus_source_update_pyproject.toml
- tests/unit/build_test/test_poetry.py
The priority for the poetry source `nexus` is set back to `default`, when running on-prem. This fixes the error where poetry would try to install packages form PyPi onprem.
If the source is already set we remove it, this is done to avoid the error that occurs when source is set with the deprecated `--default` option like we did before: `poetry source add --default nexus "echo $PIP_INDEX_URL"`.
If the source is not removed beforehand this results in the error:
```
~/uhv-oljegass (main)$ poetry source add --priority=default nexus `echo $PIP_INDEX_URL`
Warning: Found deprecated key 'default' or 'secondary' in pyproject.toml configuration for source nexus. Please provide the key 'priority' instead. Accepted values are: 'default', 'primary', 'secondary', 'supplemental', 'explicit'.
Source with …
```
> Restoring Default Priority for Poetry Source Nexus and Resolving Deprecation Issue

- .github/workflows/documentation.yml
The documentation page is very outdated because the deploy action is never triggered.
https://statisticsnorway.github.io/ssb-project-cli/
> Correct trigger for documentation

- noxfile.py
- poetry.lock
- pyproject.toml
- src/ssb_project_cli/ssb_project/app.py
- src/ssb_project_cli/ssb_project/build/build.py
- src/ssb_project_cli/ssb_project/build/poetry.py
- src/ssb_project_cli/ssb_project/util.py
- tests/unit/build_test/test_build.py
- tests/unit/test_utils.py
- Three methods with fallback for discovering project root and name.
- Used for create and build.
- Fix for #253
> :bug: Robust method for discovering project name

- src/ssb_project_cli/ssb_project/create/create.py
- tests/unit/test_utils.py
This PR solves the problem where we check the wrong disk for diskspace while ssb-project is running on-prem.
Ref: https://ssb-norge.slack.com/archives/C015E7B4YS0/p1695126307603229?thread_ts=1695044075.952239&cid=C015E7B4YS0
> added conditional code to choose what disk to check

- src/ssb_project_cli/ssb_project/create/github.py
Issue in PyGithub has been patched:
https://github.com/PyGithub/PyGithub/issues/2578
And backported:
https://github.com/PyGithub/PyGithub/issues/2719
..so we can remove the workaround
> Remove unused arg 'user_bypass_pull_request_allowances=[]'

- src/ssb_project_cli/ssb_project/create/local_repo.py
When resetting the git configuration in an existing project, we created a project in a temporary directory, and copied over the .gitattributes and .gitignore files from that project into our current directory. 
However, there was a missing argument when creating the project in the tempdir, which caused the project to be created in the *current* directory. This then caused the copying operation to fail.
> Fix template bug

- .github/workflows/release.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
- poetry.lock
- src/ssb_project_cli/ssb_project/build/build.py
- src/ssb_project_cli/ssb_project/build/poetry.py
- src/ssb_project_cli/ssb_project/create/local_repo.py
- tests/unit/build_test/test_build.py
- tests/unit/build_test/test_poetry.py
- tests/unit/create_test/test_local_repo.py
It is a maintenance issue to have templates containing a poetry.lock file. The templates need to be updated when vulnerabilities in poetry.lock are found, and when instances of the template are updated with `cruft update`, it almost always shows conflicts in `poetry.lock`. With this PR  `poetry update --lock` is run after create, to get a fresh and updated `poetry.lock` file and the templates does not need to have a `poetry.lock` file.
There are 3 commits. The first one adds and use the function `poetry_update_lockfile_dependencies`.
The second one makes it work onprem too. Extracted code to a `check_and_fix_onprem_source`-function, and had to move it to `poetry.py` to avoid circular dependencies.
The third one is mainly update of GitHub Actions versions, and some fixes to make it work …
> Support templates without poetry.lock

- src/ssb_project_cli/ssb_project/app.py
- src/ssb_project_cli/ssb_project/util.py
Expose the no_kernel argument to the `build` command. Now also supports reading from the environment variable NO_KERNEL for both `create` and `build` commands.
> Add no_kernel argument to ssb-project build

- pyproject.toml
- src/ssb_project_cli/ssb_project/app.py
- src/ssb_project_cli/ssb_project/create/create.py
- tests/unit/create_test/test_create.py
You can now pass `--name` and `--email` instead of typing them interactively. This is useful when calling `ssb-project` programatically.
> ssb-project create: support name and email args

- .github/workflows/release.yml
This project is using an old cookiecutter template, until now this stop-gap is removing publishing to testpypi for releasing to continue
> Remove publishing to test.pypi

- src/ssb_project_cli/ssb_project/app.py
- tests/integration/test_create.py
- tests/unit/test_cli.py
The implementation of --no-verify for the create command was such that
the flag had no effect. Invert the logic of the flag such that its
presence actually disables verification.
> Fix --no-verify flag
